version: "3.3"
services:
    frontend-nginx:
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - "80:80"   # Outbound traffic on port 80
                        # TODO: change to ssh on deploy
        networks:
            - main-internal-network
        restart: unless-stopped
        depends_on:
            - backend-node
    backend-node:
        build:
            context: ./backend
            dockerfile: dockerfile
        networks:
            - main-internal-network
        restart: unless-stopped
networks:
    # Cross Application Networks
    main-internal-network:
        driver: bridge