version: "3.3"
services:
    frontend-nginx:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"   # Listening on port 80
        networks:
            - main-internal-network
        restart: unless-stopped
networks:
    # Application Network
    main-internal-network:
        driver: bridge